//
//  FullScreenImageInteractor.swift
//  Kiliaro
//
//  Created by Milad on 9/19/1400 AP.
//  Copyright (c) 1400 AP ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FullScreenImageBusinessLogic
{
    func doSomething(request: FullScreenImage.Something.Request)
}

protocol FullScreenImageDataStore
{
    var media: SharedMedia? { get set }
    var placeHolder: UIImage? { get set }
}

class FullScreenImageInteractor: FullScreenImageBusinessLogic, FullScreenImageDataStore
{
    var presenter: FullScreenImagePresentationLogic?
    var worker: FullScreenImageWorker?
    var media: SharedMedia?
    var placeHolder: UIImage?
    
    // MARK: Do something
    
    func doSomething(request: FullScreenImage.Something.Request)
    {
        worker = FullScreenImageWorker()
        worker?.doSomeWork()
        
        let response = FullScreenImage.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
