//
//  FullScreenImageViewController.swift
//  Kiliaro
//
//  Created by Milad on 9/19/1400 AP.
//  Copyright (c) 1400 AP ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FullScreenImageDisplayLogic: class
{
  func displaySomething(viewModel: FullScreenImage.Something.ViewModel)
}

class FullScreenImageViewController: UIViewController, FullScreenImageDisplayLogic
{
  var interactor: FullScreenImageBusinessLogic?
  var router: (NSObjectProtocol & FullScreenImageRoutingLogic & FullScreenImageDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = FullScreenImageInteractor()
    let presenter = FullScreenImagePresenter()
    let router = FullScreenImageRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    setupUI()
      
  }
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        self.navigationController?.navigationBar.alpha = 1
        self.navigationController?.navigationBar.prefersLargeTitles = false
        
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        self.navigationController?.navigationBar.prefersLargeTitles = true
    }
  
  // MARK: Do something
  
    @IBOutlet weak var image: UIImageView!
    @IBOutlet weak var scrollView: UIScrollView!
    @IBOutlet weak var dateLabel: UILabel!
    @IBOutlet weak var activityView: UIActivityIndicatorView!
    
    func setupUI() {
        guard let media = router?.dataStore?.media else { fatalError()}
        guard let placeHolder = router?.dataStore?.placeHolder else { fatalError()}
        
        // Hardcode replacement. should be done with date formatter
        self.dateLabel.text = media.createdAt.replacingOccurrences(of: "T", with: " ").dropLast(4).description
        
        self.image.sd_setImage(with: URL(string: media.thumbnailUrl)!, placeholderImage: placeHolder, completed: {[weak self] _,_,_,_ in
            self?.activityView.stopAnimating()
        })
        
        scrollView.contentSize = image.frame.size
        scrollView.minimumZoomScale = 1
        scrollView.maximumZoomScale = 5.0
    }
  
  func displaySomething(viewModel: FullScreenImage.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}


extension FullScreenImageViewController: UIScrollViewDelegate {
    func viewForZooming(in scrollView: UIScrollView) -> UIView? {
        return self.image
    }
}
