//
//  MainModels.swift
//  Kiliaro
//
//  Created by Milad on 9/19/1400 AP.
//  Copyright (c) 1400 AP ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MainModel
{
  // MARK: Use cases
  
  enum SharedMediaModel
  {
    struct Request
    {
        let offset: Int
        let limit: Int
    }
    struct Response
    {
        let result: [SharedMedia]
    }
    struct ViewModel
    {
        let result: [SharedMedia]
    }
  }
}
