//
//  MainInteractor.swift
//  Kiliaro
//
//  Created by Milad on 9/19/1400 AP.
//  Copyright (c) 1400 AP ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainBusinessLogic
{
    func getSharedMedia(request: MainModel.SharedMediaModel.Request)
    func setDataStore(media: SharedMedia, placeHolder: UIImage?)
}

protocol MainDataStore
{
    var media: SharedMedia? { get set }
    var placeHolder: UIImage? { get set }
}

class MainInteractor: MainBusinessLogic, MainDataStore
{
    var presenter: MainPresentationLogic?
    var worker: MainWorker?
    var media: SharedMedia?
    var placeHolder: UIImage?
  
  // MARK: Do something
  
    func getSharedMedia(request: MainModel.SharedMediaModel.Request) {
        worker = MainWorker()
        worker?.getSharedMedia(request: request, completion: {[weak self] response in
            self?.presenter?.presentSharedMedia(response: response)
        })
    }
    func setDataStore(media: SharedMedia, placeHolder: UIImage?) {
        self.media = media
        self.placeHolder = placeHolder
        presenter?.presentRouting()
    }
  
}
