//
//  MainPresenter.swift
//  Kiliaro
//
//  Created by Milad on 9/19/1400 AP.
//  Copyright (c) 1400 AP ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPresentationLogic
{
    func presentSharedMedia(response: MainModel.SharedMediaModel.Response)
    func presentRouting(media: SharedMedia)
}

class MainPresenter: MainPresentationLogic
{
  weak var viewController: MainDisplayLogic?
  
  // MARK: Do something
  
    func presentSharedMedia(response: MainModel.SharedMediaModel.Response) {
        let viewModel = MainModel.SharedMediaModel.ViewModel(result: response.result)
        viewController?.displaySharedMedia(viewModel: viewModel)
    }
    func presentRouting(media: SharedMedia) {
        viewController?.displayDataPassing(media: media)
    }
}
