//
//  MainRouter.swift
//  Kiliaro
//
//  Created by Milad on 9/19/1400 AP.
//  Copyright (c) 1400 AP ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MainRoutingLogic
{
  func routToFullScreen()
}

protocol MainDataPassing
{
  var dataStore: MainDataStore? { get }
}

class MainRouter: NSObject, MainRoutingLogic, MainDataPassing
{
  weak var viewController: MainViewController?
  var dataStore: MainDataStore?
  
  // MARK: Routing
  
    func routToFullScreen() {
        let storyboard = UIStoryboard(name: "FullScreenImage", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "FullScreenImageViewController") as! FullScreenImageViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToFullScreen(source: dataStore!, destination: &destinationDS)
        navigateToFullScreen(source: viewController!, destination: destinationVC)
    }
    
    func navigateToFullScreen(source: MainViewController, destination: FullScreenImageViewController)
    {
        source.show(destination, sender: nil)
        //source.present(destination, animated: true, completion: nil)
        
    }
    
    func passDataToFullScreen(source: MainDataStore, destination: inout FullScreenImageDataStore)
    {
        destination.media = source.media
        destination.placeHolder = source.placeHolder
    }
    
}
